sudo: required
services:
- docker
language: java
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
deploy:
- skip_cleanup: true
  on:
    branch: master
    tags: true
  provider: releases
  api_key:
    secure: "cuI1epB4H2vvld/tBVtUEL7CZxpoDBN2ZX+sSNWGFPvi2vloG48/kcAhODv4lmmu7uY1mu2iwcodXujxUlk8kYKHRIttyZGmeaIpu26o0SYawS80HUm0+OX7DJF9wz6RwJ9KLIS6Aw9Vbw7/t2yYJ7Q1ElqSh/ntrh70qkvqnhm1QgjDatwtCcAIe02qrz8Jtpy/y1OWoZ8uVJ+bhUmnppbzq9y8/iSBP3O34IE0sGXczpV0s2N3MH+jQaZVH2sFzGGln4PEet3FO9mFY2Od8XvrFLcW6VXZZjiOKAyXgGWZk4WxJO3KDFC0ji4kMXgeb3V8dlSJ5b2AMJvNZeOkS2XUUlrHj6spNfnaVpzADma0KBXvHIRaO5HQeXwsvL//T9ztCLq5mDrYcdzsy72Zp9zw/K/XSGcfXvoFsQjD/PgtNTwngFqo9Ww0LH2aLSrh7jjgbYJUA5f9vlYYWX/3sdktccAwcIJyO++miM0C4GriNosHvEO+NC8LOj81Jodoksd8LGEhlKhJCuxsrSil2v+XZtlyDYKl5Cc1R3Vq2WgDv86RzfwIhMj7TUJwwjuGQ2PXD383wqTTQW6TYCvMvc8ldLIbZJdtx7VmE+RtNuKcpSlVw6pFmF44Dz6soy98VSW0x/P7aPb5jA8Azhw2sRwU0vK5Xyn5e85tCqBRoTw="
  file: build/libs/ansible-plugin-${TRAVIS_TAG}.jar
- skip_cleanup: true
  on:
    branch: master
    tags: true
  provider: script
  script: bash deploy-docker.sh
