sudo: required
services:
- docker
language: java
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
deploy:
- skip_cleanup: true
  on:
    branch: master
    tags: true
  provider: releases
  api_key:
    secure: QfAzIt0BYCRVgDhseZvCwnGD9jgMjnhjXWNXxHFTM4wKiRKhbNuolKD0Djk0MhJF8/Bnncx5vUwnuGTPwI3SvdLep2X4eKLUmc1DyCeZJ+H9zO9jCRYLmJ2R9gQvhX3aWP9gzrRNzuzLhXnhjXlN04FB3EDF/lkf21WebDwQgSBIEZZmP8AV6N8ZJ8+aJARTWDAave36HRZ86EPKAoPyLDxEvnpoteC9eJ7//7GutAnDIGgM7L3+TeR5PBwq+Aiqf5xWyIgUGlAkFPNr5SqfJKH4WJEFZTnDSjH5W7vCgZ2NlbLgCNhHLTbNKrb0flOlbLx08xCozqLW6EsZ+uk8OSFa1nuXC259SU5T0osCtshMt2a48PDtC1JRjFCjLHBulpqy+R899N+iFu67n7p+b/wxD1sIiIVL1o6hmjILBG6mPPy3bHw6UIftdDbuhBTdTWMsJlBrKoYv3bVB/WmtMQkd/+MdTbdi9hNToSP5iMICgPcEvNnlV7vtIuLVrE659iphkPetDZjRFvTMzm9TrQLg4gsbkaaMQWeQOZdRB6Yma5jtqG7m0HPLcNthhUg6PbrfLEQhOIPU6uvMOn6j7O6Rp/Y3r5LERTsVrLCDyZGJUzBcEEqjI84AIB6RoaijOI2tV9aKf8FDQyktjTgK63bz9uUnEFlocJ3CBUBIDiM=
  file: build/libs/ansible-plugin-${TRAVIS_TAG}.jar
- skip_cleanup: true
  on:
    branch: master
    tags: true
  provider: script
  script: bash deploy-docker.sh
