---
- hosts: all
  vars:
    facts: True
  gather_facts: "{{facts}}"
  serial: 10
  tasks:
    - local_action: file path="{{tmpdir}}/data" state=directory
      run_once: yes
    - local_action: template src=host-tpl.j2 dest="{{tmpdir}}/data/{{inventory_hostname}}"
