---
- hosts: all
  vars:
    facts: True
  gather_facts: "{{facts}}"
  tasks:
    - local_action: file path=data state=directory
      run_once: yes
    - local_action: template src=host-tpl.j2 dest="data/{{inventory_hostname}}"
